### ISSUE TITLE
SQL dependency?

### ISSUE THREAD

**Issue by starseeker** [s-bear/image-hash#1]
Hi!  Is work still proceeding on this code?  When I attempt to build without SQLite I get a compile error.

**Comment by s-bear** [comment]
I'm not really working on it anymore--I had a pretty specific task that I developed it for, which is now complete (finding the source of a screenshot out of a lot of extremely similar videos).
The code does require sqlite to store the data structures -- it's included in the vcpkg manifest, but I can see that it's not in the readme.

**Comment by s-bear** [comment]
After reading the code while fixing the resampling error, it looks like I intended sqlite to be an optional dependency! I haven't tested rebuilding without it, but I added a few more preprocessor guards that I believe will let you compile without sqlite. Let me know how you get on. --Sam

**Comment by starseeker** [comment]
Yep, that worked - building without SQLlite now, thank you!
